version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: presentation_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=https://fleetbase.paylab.kz:8081
      - DATABASE_URL=file:./dev.db
    volumes:
      - backend_data:/app/prisma
    networks:
      - presentation_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_URL=https://fleetbase.paylab.kz:8081
    container_name: presentation_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: [backend]
    networks:
      - presentation_network

volumes:
  backend_data:
    driver: local

networks:
  presentation_network:
    driver: bridge